### ISSUE TITLE
Miscellaneous To-Do

### ISSUE THREAD

**Issue by NachoToast** [Weebs-Incorporated/AIMS#20]
# API Spec

- [x] Ensure all JSON schemas have `"type": "object"`.
- [x] Ensure all properties are in strictCamelCase and not snake_case.
- [x] Ensure all handlers that have request and response bodies use [this syntax](https://github.com/Weebs-Incorporated/AIMS/blob/db3e82a62773b6bad3979a61db7d32ef80713162/src/handlers/submissionProcess/modifySubmission.ts#L5-L9).

# Tests
- [x] Make sure all `requests()` are assigned to variables called `res` and not `req`.

# Codebase
- [x] Make sure all response messages (in both API spec and source code) end with a period (excluding 401 messages) and start with a capitalized letter.
